Script debug

diff --git a/bacchus-system-updater/src/sbin/bacchus-system-updater b/bacchus-system-updater/src/sbin/bacchus-system-updater
--- a/bacchus-system-updater/src/sbin/bacchus-system-updater
+++ b/bacchus-system-updater/src/sbin/bacchus-system-updater
@@ -52,51 +52,62 @@ function get_last_received_snapshot() {
 }
 
 function download_images() {
-	rsync -a --rsh "ssh -i \"${SSH_IDENTITY}\" -l \"${SSH_USER}\"" --update --delete "${IMAGE_SERVER}:${IMAGE_SERVER_PATH}/" "${BTRFS_TOPLEVEL}/images/"
+	rsync -rt --chmod 600 --rsh "ssh -i \"${SSH_IDENTITY}\" -o StrictHostKeyChecking=no -l \"${SSH_USER}\"" --update --delete "${IMAGE_SERVER}:${IMAGE_SERVER_PATH}/" "${BTRFS_TOPLEVEL}/images/" || die "Btrfs image download failed"
 	
-	while read file; do
+	find "${BTRFS_TOPLEVEL}/images" -type f -not -name '*.sig' -size '+0' | while read file; do
 		if [ ! -f "${file}.sig" ]; then
 			error "${file} is not signed!"
 			rm "${file}" || die "Deleting ${file} failed"
 		fi
 
 		gpg --no-default-keyring --keyring "${KEYRING}" --verify "${file}.sig" "${file}" 2>/dev/null 1>/dev/null
-		if [ "$?" -ne 0 ] ; then
+		if [ $? -ne 0 ]; then
 			error "Sign verification failed: ${file}"
 			rm "${file}" "${file}.sig" || die "Deleting ${file} and ${file}.sig failed"
 		fi
-	done <<< "$(find "${BTRFS_TOPLEVEL}/images" -not -name '*.sig')"
+	done || exit 1
 }
 
 function btrfs_receive() {
 	local last_received_snapshot="${1}"
 	local btrfs_image
 
-	while read btrfs_image; do
-		if [ "${btrfs_image}" \> "${last_received_snapshot}" ]; then
+	find "${BTRFS_TOPLEVEL}/images" -type f -not -name '*.sig' | sort | while read btrfs_image; do
+		if [ "${btrfs_image##*/}" \> "${last_received_snapshot}" ]; then
 			btrfs receive -f "${btrfs_image}" "${BTRFS_TOPLEVEL}/snapshots" || die "Receive ${btrfs_image} failed"
 			truncate --size 0 "${btrfs_image}"
 		fi
-	done <<< "$(find "${BTRFS_TOPLEVEL}/images" -not -name '*.sig' | sort)"
+	done || exit 1
 }
 
 function update_root_subvolume() {
 	local last_received_snapshot="${1}"
-	local new_root="$(find "${BTRFS_TOPLEVEL}/images" -not -name '*.sig' | sort | tail -n 1)" || die "Getting new root failed"
+	local new_root="$(find "${BTRFS_TOPLEVEL}/images" -type f -not -name '*.sig' | sort | tail -n 1)" || die "Getting new root failed"
+	local current_root="$(btrfs subvolume show / | head -n 2 | tail -n 1 | awk -F ' ' '{print $2}')" || die "Getting current root failed"
+	new_root="${new_root##*/}"
 
-	if [ "${last_received_snapshot}" == "${new_root}" ]; then
+	if [ "${new_root}" == "" ]; then
+		return 0
+	elif [ "${last_received_snapshot}" == "${new_root}" ]; then
 		return 0
 	fi
 
-	btrfs subvolume delete "${BTRFS_TOPLEVEL}/old-root" 2>/dev/null 1>/dev/null
-	btrfs subvolume delete "${BTRFS_TOPLEVEL}/root" 2>/dev/null 1>/dev/null
+	if [ "${current_root}" == "root" ]; then
+		btrfs subvolume delete "${BTRFS_TOPLEVEL}/old-root" 2>/dev/null 1>/dev/null
 
-	if [ -d "${BTRFS_TOPLEVEL}/root" ]; then
 		if [ -d "${BTRFS_TOPLEVEL}/old-root" ]; then
-			die "Btrfs subvolume delete failed"
+			die "Btrfs old-root subvolume delete failed"
 		fi
 
 		mv "${BTRFS_TOPLEVEL}/root" "${BTRFS_TOPLEVEL}/old-root" || die "Moving btrfs root subvolume failed"
+	elif [ "${current_root}" == "old-root" ]; then
+		btrfs subvolume delete "${BTRFS_TOPLEVEL}/root" 2>/dev/null 1>/dev/null
+
+		if [ -d "${BTRFS_TOPLEVEL}/root" ]; then
+			die "Btrfs root subvolume delete failed"
+		fi
+	else
+		die "Unknown current root ${current_root}"
 	fi
 
 	btrfs subvolume snapshot -r "${BTRFS_TOPLEVEL}/snapshots/${new_root}" "${BTRFS_TOPLEVEL}/root" || die "Creating root subvolume failed"
@@ -105,13 +116,17 @@ function update_root_subvolume() {
 }
 
 function clean_up_snapshots() {
-	local new_root="$(find "${BTRFS_TOPLEVEL}/snapshots" | sort | tail -n 1)" || die "Getting new root failed"
+	local new_root="$(find "${BTRFS_TOPLEVEL}/snapshots" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)" || die "Getting new root failed"
 
-	while read btrfs_snapshot; do
+	if [ "${new_root}" == "" ]; then
+		return 0
+	fi
+
+	find "${BTRFS_TOPLEVEL}/snapshots" -mindepth 1 -maxdepth 1 -type d | while read btrfs_snapshot; do
 		if [ "${btrfs_snapshot}" != "${new_root}" ]; then
 			btrfs subvolume delete "${btrfs_snapshot}" || error "Deleting snapshot ${btrfs_snapshot} failed"
 		fi
-	done <<< "$(find "${BTRFS_TOPLEVEL}/snapshots")"
+	done
 }
 
 main "$@"
